package gitignore

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kgatilin/myhome/internal/config"
)

const header = "# Auto-generated by myhome — do not edit manually\n"

// Static rules for common directories/files that should always be ignored
// in a git-tracked home folder.
var staticRules = []string{
	"# macOS system",
	".Trash/",
	"Library/",
	"Applications/",
	"Desktop/",
	"Documents/",
	"Downloads/",
	"Movies/",
	"Music/",
	"Pictures/",
	"Public/",
	"",
	"# Caches and state",
	".cache/",
	".local/",
	".npm/",
	".cargo/",
	".rustup/",
	".go/",
	"go/",
	".docker/",
	".lima/",
	".orbstack/",
	".colima/",
	".kube/",
	".terraform.d/",
	".vault-token",
	".vscode/",
	".cursor/",
	"",
	"# Secrets and credentials (never track)",
	".secrets/",
	".ssh/id_*",
	".ssh/known_hosts",
	".gnupg/",
	".keepassxc/",
	"*.kdbx",
	"*.key",
	"",
	"# Tool state",
	".mise/",
	".local/share/mise/",
	".config/",
	"",
	"# myhome state",
	".myhome-state.yml",
	"",
	"# Logs",
	"tasks/logs/",
	"",
	"# Git backups",
	".git-backups/",
	"",
	"# Archives",
	"archive/",
	"",
	"# Containers",
	"containers/",
}

// Generate creates the .gitignore content from static rules + repo paths.
func Generate(cfg *config.Config) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n")

	// Static rules
	for _, rule := range staticRules {
		b.WriteString(rule)
		b.WriteString("\n")
	}

	// Dynamic rules from repos
	if len(cfg.Repos) > 0 {
		b.WriteString("\n# Repos (cloned by myhome)\n")
		for _, r := range cfg.Repos {
			b.WriteString(r.Path)
			b.WriteString("/\n")
		}
	}

	return b.String()
}

// Write generates and writes .gitignore to the home directory.
func Write(cfg *config.Config, homeDir string) error {
	content := Generate(cfg)
	path := filepath.Join(homeDir, ".gitignore")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}
	return nil
}
