package gitignore

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kgatilin/myhome/internal/config"
)

func TestGenerate(t *testing.T) {
	cfg := &config.Config{
		Repos: []config.Repo{
			{Path: "dev/tools/myhome", Env: "base"},
			{Path: "work/uagent", Env: "work"},
		},
	}

	content := Generate(cfg)

	// Check header
	if !strings.HasPrefix(content, "# Auto-generated by myhome") {
		t.Error("missing header")
	}

	// Check static rules present
	staticChecks := []string{".Trash/", ".cache/", ".secrets/", ".myhome-state.yml"}
	for _, s := range staticChecks {
		if !strings.Contains(content, s) {
			t.Errorf("missing static rule: %s", s)
		}
	}

	// Check repo paths
	if !strings.Contains(content, "dev/tools/myhome/") {
		t.Error("missing repo path: dev/tools/myhome/")
	}
	if !strings.Contains(content, "work/uagent/") {
		t.Error("missing repo path: work/uagent/")
	}
}

func TestGenerateNoRepos(t *testing.T) {
	cfg := &config.Config{}
	content := Generate(cfg)
	if strings.Contains(content, "# Repos") {
		t.Error("should not have repos section when no repos configured")
	}
}

func TestWrite(t *testing.T) {
	homeDir := t.TempDir()
	cfg := &config.Config{
		Repos: []config.Repo{
			{Path: "dev/test", Env: "base"},
		},
	}

	if err := Write(cfg, homeDir); err != nil {
		t.Fatalf("Write() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(homeDir, ".gitignore"))
	if err != nil {
		t.Fatalf("read .gitignore: %v", err)
	}
	if !strings.Contains(string(data), "dev/test/") {
		t.Error("written file missing repo path")
	}
}
