package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kgatilin/myhome/internal/config"
	"github.com/kgatilin/myhome/internal/platform"
)

const testInitConfig = `
envs:
  base:
    include: [base]
  work:
    include: [base, work]

repos:
  - path: dev/tools/myhome
    url: git@github.com:kgatilin/myhome.git
    env: base

tools:
  base:
    go: "1.26"

packages:
  base:
    brew: [git]
    apt: [git]

auth:
  github.com:
    key: id_personal
`

// mockPlatform implements platform.Platform for testing without real system calls.
type mockPlatform struct{}

func (m *mockPlatform) OS() string                                                  { return "linux" }
func (m *mockPlatform) HomeDir() string                                             { return "/home" }
func (m *mockPlatform) UserHome(username string) string                             { return "/home/" + username }
func (m *mockPlatform) CreateUser(username string) error                            { return nil }
func (m *mockPlatform) RemoveUser(username string, removeHome bool) error           { return nil }
func (m *mockPlatform) CreateGroup(group string) error                              { return nil }
func (m *mockPlatform) AddUserToGroup(username, group string) error                 { return nil }
func (m *mockPlatform) SetReadOnlyACL(username, path string) error                  { return nil }
func (m *mockPlatform) PackageManager() string                                      { return "apt" }
func (m *mockPlatform) InstallPackages(packages []string) error                     { return nil }
func (m *mockPlatform) InstallCaskPackages(packages []string) error                 { return nil }
func (m *mockPlatform) ListInstalledPackages() ([]string, error)                    { return []string{"git"}, nil }
func (m *mockPlatform) ServiceInstall(name string, args []string, username string, restart bool) error { return nil }
func (m *mockPlatform) ServiceStart(name string) error                              { return nil }
func (m *mockPlatform) ServiceStop(name string) error                               { return nil }
func (m *mockPlatform) ServiceStatus(name string) (bool, error)                     { return false, nil }

// Verify mockPlatform satisfies the interface at compile time.
var _ platform.Platform = (*mockPlatform)(nil)

func TestRunInit(t *testing.T) {
	homeDir := t.TempDir()
	configDir := filepath.Join(homeDir, "setup")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}

	configPath := filepath.Join(configDir, "myhome.yml")
	if err := os.WriteFile(configPath, []byte(testInitConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	statePath := filepath.Join(homeDir, ".myhome-state.yml")
	plat := &mockPlatform{}

	err := runInit("base", configPath, homeDir, statePath, plat)
	if err != nil {
		t.Fatalf("runInit failed: %v", err)
	}

	// Verify state file
	state, err := config.LoadState(statePath)
	if err != nil {
		t.Fatalf("load state: %v", err)
	}
	if state.CurrentEnv != "base" {
		t.Errorf("state.CurrentEnv = %q, want %q", state.CurrentEnv, "base")
	}

	// Verify .gitignore was generated
	gitignorePath := filepath.Join(homeDir, ".gitignore")
	data, err := os.ReadFile(gitignorePath)
	if err != nil {
		t.Fatalf("read .gitignore: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "Auto-generated by myhome") {
		t.Error(".gitignore missing header")
	}
	if !strings.Contains(content, "dev/tools/myhome/") {
		t.Error(".gitignore missing repo path")
	}

	// Verify .ssh/config was generated
	sshConfigPath := filepath.Join(homeDir, ".ssh", "config")
	sshData, err := os.ReadFile(sshConfigPath)
	if err != nil {
		t.Fatalf("read .ssh/config: %v", err)
	}
	sshContent := string(sshData)
	if !strings.Contains(sshContent, "Host github.com") {
		t.Error(".ssh/config missing github.com host")
	}
	if !strings.Contains(sshContent, "id_personal") {
		t.Error(".ssh/config missing key reference")
	}

	// Verify .gitconfig was generated (auth entries exist, so identity step should run)
	gitconfigPath := filepath.Join(homeDir, ".gitconfig")
	gcData, err := os.ReadFile(gitconfigPath)
	if err != nil {
		t.Fatalf("read .gitconfig: %v", err)
	}
	if !strings.Contains(string(gcData), "[user]") {
		t.Error(".gitconfig missing [user] section")
	}

	// Verify .mise.toml was generated (tools.Sync writes it; mise install may fail, that's ok)
	miseTomlPath := filepath.Join(homeDir, ".mise.toml")
	miseData, err := os.ReadFile(miseTomlPath)
	if err != nil {
		t.Fatalf("read .mise.toml: %v", err)
	}
	if !strings.Contains(string(miseData), "go") {
		t.Error(".mise.toml missing go tool")
	}
}

func TestRunInitCreatesDefaultConfig(t *testing.T) {
	homeDir := t.TempDir()
	configPath := filepath.Join(homeDir, "setup", "myhome.yml")
	statePath := filepath.Join(homeDir, ".myhome-state.yml")
	plat := &mockPlatform{}

	// Config does not exist — runInit should create a default
	err := runInit("base", configPath, homeDir, statePath, plat)
	if err != nil {
		t.Fatalf("runInit failed: %v", err)
	}

	// Verify config was created
	if _, err := os.Stat(configPath); err != nil {
		t.Fatalf("default config not created: %v", err)
	}

	// Verify it's valid YAML that can be loaded
	cfg, err := config.Load(configPath)
	if err != nil {
		t.Fatalf("load default config: %v", err)
	}
	if _, ok := cfg.Envs["base"]; !ok {
		t.Error("default config missing 'base' env")
	}
}

func TestRunInitWorkEnv(t *testing.T) {
	homeDir := t.TempDir()
	configDir := filepath.Join(homeDir, "setup")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}

	configPath := filepath.Join(configDir, "myhome.yml")
	if err := os.WriteFile(configPath, []byte(testInitConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	statePath := filepath.Join(homeDir, ".myhome-state.yml")
	plat := &mockPlatform{}

	err := runInit("work", configPath, homeDir, statePath, plat)
	if err != nil {
		t.Fatalf("runInit failed: %v", err)
	}

	state, err := config.LoadState(statePath)
	if err != nil {
		t.Fatalf("load state: %v", err)
	}
	if state.CurrentEnv != "work" {
		t.Errorf("state.CurrentEnv = %q, want %q", state.CurrentEnv, "work")
	}
}

func TestRunInitUnknownEnv(t *testing.T) {
	homeDir := t.TempDir()
	configDir := filepath.Join(homeDir, "setup")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}

	configPath := filepath.Join(configDir, "myhome.yml")
	if err := os.WriteFile(configPath, []byte(testInitConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	statePath := filepath.Join(homeDir, ".myhome-state.yml")
	plat := &mockPlatform{}

	err := runInit("nonexistent", configPath, homeDir, statePath, plat)
	if err == nil {
		t.Error("expected error for unknown env")
	}
	if !strings.Contains(err.Error(), "resolve env") {
		t.Errorf("error = %q, want it to mention 'resolve env'", err.Error())
	}
}
