package tools

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateMiseToml(t *testing.T) {
	tools := map[string]string{
		"go":     "1.26",
		"python": "3.11",
		"node":   "20",
	}
	content := GenerateMiseToml(tools)

	if !strings.HasPrefix(content, "# Auto-generated by myhome") {
		t.Error("missing header")
	}
	if !strings.Contains(content, "[tools]") {
		t.Error("missing [tools] section")
	}
	if !strings.Contains(content, `go = "1.26"`) {
		t.Error("missing go tool")
	}
	if !strings.Contains(content, `python = "3.11"`) {
		t.Error("missing python tool")
	}
}

func TestGenerateMiseTomlDeterministic(t *testing.T) {
	tools := map[string]string{"go": "1.26", "python": "3.11", "node": "20"}
	a := GenerateMiseToml(tools)
	b := GenerateMiseToml(tools)
	if a != b {
		t.Error("output should be deterministic")
	}
}

func TestGenerateMiseTomlSorted(t *testing.T) {
	tools := map[string]string{"zsh": "5.9", "go": "1.26", "node": "20"}
	content := GenerateMiseToml(tools)
	goIdx := strings.Index(content, "go =")
	nodeIdx := strings.Index(content, "node =")
	zshIdx := strings.Index(content, "zsh =")
	if goIdx > nodeIdx || nodeIdx > zshIdx {
		t.Error("tools should be sorted alphabetically")
	}
}

func TestWriteMiseToml(t *testing.T) {
	homeDir := t.TempDir()
	tools := map[string]string{"go": "1.26"}

	if err := WriteMiseToml(tools, homeDir); err != nil {
		t.Fatalf("WriteMiseToml() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(homeDir, ".mise.toml"))
	if err != nil {
		t.Fatalf("read .mise.toml: %v", err)
	}
	if !strings.Contains(string(data), `go = "1.26"`) {
		t.Error("written file missing go tool")
	}
}

func TestParseMiseList(t *testing.T) {
	// Simplified JSON output from mise ls --current --json
	output := `{
  "go": [
    {
      "version": "1.26.1",
      "source": "~/.mise.toml"
    }
  ],
  "python": [
    {
      "version": "3.11.5",
      "source": "~/.mise.toml"
    }
  ]
}`
	result := parseMiseList(output)
	if result["go"] != "1.26.1" {
		t.Errorf("go = %q, want 1.26.1", result["go"])
	}
	if result["python"] != "3.11.5" {
		t.Errorf("python = %q, want 3.11.5", result["python"])
	}
}

func TestList(t *testing.T) {
	expected := map[string]string{
		"go":     "1.26",
		"python": "3.11",
	}
	// List will try to call mise (may not be installed in test env)
	statuses, err := List(expected)
	if err != nil {
		t.Fatalf("List() error: %v", err)
	}
	if len(statuses) != 2 {
		t.Fatalf("got %d statuses, want 2", len(statuses))
	}
	// Should be sorted
	if statuses[0].Name != "go" {
		t.Errorf("first tool = %q, want go", statuses[0].Name)
	}
}
