package tools

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// ToolStatus describes the state of a tool runtime.
type ToolStatus struct {
	Name     string
	Expected string
	Installed string // empty if not installed
}

// GenerateMiseToml produces .mise.toml content from a merged tool map.
func GenerateMiseToml(tools map[string]string) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by myhome — do not edit manually\n\n")
	b.WriteString("[tools]\n")

	// Sort for deterministic output
	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		fmt.Fprintf(&b, "%s = %q\n", name, tools[name])
	}

	return b.String()
}

// WriteMiseToml generates and writes ~/.mise.toml.
func WriteMiseToml(tools map[string]string, homeDir string) error {
	content := GenerateMiseToml(tools)
	path := filepath.Join(homeDir, ".mise.toml")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write .mise.toml: %w", err)
	}
	return nil
}

// Install runs `mise install` to install all configured tools.
func Install() error {
	cmd := exec.Command("mise", "install")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("mise install: %w", err)
	}
	return nil
}

// Sync generates .mise.toml and runs mise install.
func Sync(tools map[string]string, homeDir string) error {
	if err := WriteMiseToml(tools, homeDir); err != nil {
		return err
	}
	return Install()
}

// List returns the status of expected tools vs what mise reports installed.
func List(expected map[string]string) ([]ToolStatus, error) {
	installed, err := listInstalled()
	if err != nil {
		return nil, err
	}

	var result []ToolStatus
	names := make([]string, 0, len(expected))
	for name := range expected {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		s := ToolStatus{
			Name:     name,
			Expected: expected[name],
		}
		if v, ok := installed[name]; ok {
			s.Installed = v
		}
		result = append(result, s)
	}
	return result, nil
}

// listInstalled queries mise for currently installed tool versions.
func listInstalled() (map[string]string, error) {
	out, err := exec.Command("mise", "ls", "--current", "--json").Output()
	if err != nil {
		// If mise is not installed, return empty
		return make(map[string]string), nil
	}
	return parseMiseList(string(out)), nil
}

// parseMiseList parses the output of `mise ls --current --json` into a tool→version map.
// The JSON format is: {"go": [{"version": "1.26"}], "python": [{"version": "3.11"}]}
// For simplicity, we do lightweight parsing without a JSON library dep (already have yaml).
func parseMiseList(output string) map[string]string {
	result := make(map[string]string)
	// Simple line-based parsing: look for "tool": [...{"version": "x.y"}...]
	// This is a simplified approach; for production we'd use encoding/json.
	lines := strings.Split(output, "\n")
	var currentTool string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		// Match tool name: "go": [
		if strings.HasSuffix(trimmed, ": [") || strings.HasSuffix(trimmed, ":[") {
			name := strings.Trim(strings.Split(trimmed, ":")[0], "\" ")
			if name != "" {
				currentTool = name
			}
		}
		// Match version: "version": "1.26"
		if currentTool != "" && strings.Contains(trimmed, "\"version\"") {
			parts := strings.SplitN(trimmed, ":", 2)
			if len(parts) == 2 {
				ver := strings.Trim(parts[1], "\" ,")
				result[currentTool] = ver
				currentTool = ""
			}
		}
	}
	return result
}
