package auth

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kgatilin/myhome/internal/config"
)

func testAuth() map[string]config.AuthHost {
	return map[string]config.AuthHost{
		"github.com":          {Key: "id_personal"},
		"gitlab.iponweb.net":  {Key: "id_work"},
	}
}

func TestGenerateSSHConfig(t *testing.T) {
	content := GenerateSSHConfig(testAuth())

	checks := []string{
		"Host github.com",
		"IdentityFile ~/.ssh/id_personal",
		"IdentitiesOnly yes",
		"Host gitlab.iponweb.net",
		"IdentityFile ~/.ssh/id_work",
	}
	for _, c := range checks {
		if !strings.Contains(content, c) {
			t.Errorf("missing: %s", c)
		}
	}

	if !strings.HasPrefix(content, "# Auto-generated by myhome") {
		t.Error("missing header")
	}
}

func TestGenerateSSHConfigDeterministic(t *testing.T) {
	a := GenerateSSHConfig(testAuth())
	b := GenerateSSHConfig(testAuth())
	if a != b {
		t.Error("output should be deterministic")
	}
}

func TestWriteSSHConfig(t *testing.T) {
	homeDir := t.TempDir()
	if err := WriteSSHConfig(testAuth(), homeDir); err != nil {
		t.Fatalf("WriteSSHConfig() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(homeDir, ".ssh", "config"))
	if err != nil {
		t.Fatalf("read ssh config: %v", err)
	}
	if !strings.Contains(string(data), "Host github.com") {
		t.Error("written file missing host entry")
	}

	// Check permissions
	info, _ := os.Stat(filepath.Join(homeDir, ".ssh", "config"))
	if info.Mode().Perm() != 0o600 {
		t.Errorf("ssh config permissions = %o, want 600", info.Mode().Perm())
	}
}

func TestListKeys(t *testing.T) {
	keys := ListKeys(testAuth())
	if len(keys) != 2 {
		t.Fatalf("got %d keys, want 2", len(keys))
	}

	// Keys should be sorted
	if keys[0].Key != "id_personal" {
		t.Errorf("first key = %q, want id_personal", keys[0].Key)
	}
	if keys[0].Hosts[0] != "github.com" {
		t.Errorf("first key hosts = %v, want [github.com]", keys[0].Hosts)
	}
}

func TestListKeysSharedKey(t *testing.T) {
	auth := map[string]config.AuthHost{
		"host1.com": {Key: "id_shared"},
		"host2.com": {Key: "id_shared"},
	}
	keys := ListKeys(auth)
	if len(keys) != 1 {
		t.Fatalf("got %d keys, want 1 (shared)", len(keys))
	}
	if len(keys[0].Hosts) != 2 {
		t.Errorf("shared key hosts = %d, want 2", len(keys[0].Hosts))
	}
}
