package auth

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kgatilin/myhome/internal/config"
)

const sshConfigHeader = "# Auto-generated by myhome — do not edit manually\n"

// KeyInfo describes an SSH key and which hosts use it.
type KeyInfo struct {
	Key   string
	Hosts []string
}

// GenerateSSHConfig produces ~/.ssh/config content from the auth section.
func GenerateSSHConfig(auth map[string]config.AuthHost) string {
	var b strings.Builder
	b.WriteString(sshConfigHeader)
	b.WriteString("\n")

	// Sort hosts for deterministic output
	hosts := make([]string, 0, len(auth))
	for host := range auth {
		hosts = append(hosts, host)
	}
	sort.Strings(hosts)

	for _, host := range hosts {
		a := auth[host]
		fmt.Fprintf(&b, "Host %s\n", host)
		fmt.Fprintf(&b, "  HostName %s\n", host)
		fmt.Fprintf(&b, "  IdentityFile ~/.ssh/%s\n", a.Key)
		b.WriteString("  IdentitiesOnly yes\n")
		b.WriteString("\n")
	}

	return b.String()
}

// WriteSSHConfig generates and writes ~/.ssh/config.
func WriteSSHConfig(auth map[string]config.AuthHost, homeDir string) error {
	content := GenerateSSHConfig(auth)
	sshDir := filepath.Join(homeDir, ".ssh")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("create .ssh dir: %w", err)
	}
	path := filepath.Join(sshDir, "config")
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write ssh config: %w", err)
	}
	return nil
}

// ListKeys returns info about each SSH key and which hosts it serves.
func ListKeys(auth map[string]config.AuthHost) []KeyInfo {
	keyMap := make(map[string][]string)
	for host, a := range auth {
		keyMap[a.Key] = append(keyMap[a.Key], host)
	}

	var keys []KeyInfo
	for key, hosts := range keyMap {
		sort.Strings(hosts)
		keys = append(keys, KeyInfo{Key: key, Hosts: hosts})
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i].Key < keys[j].Key })
	return keys
}
