package identity

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Identity maps a directory pattern to a git user/email.
type Identity struct {
	Dir   string // directory pattern (e.g., "~/work/")
	Name  string
	Email string
}

// GenerateGitconfig produces .gitconfig content with includeIf directives.
func GenerateGitconfig(defaultName, defaultEmail string, overrides []Identity) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by myhome — do not edit manually\n\n")
	b.WriteString("[user]\n")
	fmt.Fprintf(&b, "  name = %s\n", defaultName)
	fmt.Fprintf(&b, "  email = %s\n", defaultEmail)
	b.WriteString("\n")

	for _, id := range overrides {
		dir := id.Dir
		if !strings.HasSuffix(dir, "/") {
			dir += "/"
		}
		fmt.Fprintf(&b, "[includeIf \"gitdir:%s\"]\n", dir)
		fmt.Fprintf(&b, "  path = %s\n", gitconfigPath(id.Dir))
		b.WriteString("\n")
	}

	return b.String()
}

// GenerateIdentityFile produces a git config fragment for a single identity override.
func GenerateIdentityFile(id Identity) string {
	var b strings.Builder
	b.WriteString("[user]\n")
	fmt.Fprintf(&b, "  name = %s\n", id.Name)
	fmt.Fprintf(&b, "  email = %s\n", id.Email)
	return b.String()
}

// WriteGitconfig writes the main .gitconfig and any identity override files.
func WriteGitconfig(homeDir, defaultName, defaultEmail string, overrides []Identity) error {
	// Write identity override files first
	for _, id := range overrides {
		content := GenerateIdentityFile(id)
		path := filepath.Join(homeDir, gitconfigPath(id.Dir))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create dir for %s: %w", path, err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write identity file %s: %w", path, err)
		}
	}

	// Write main .gitconfig
	content := GenerateGitconfig(defaultName, defaultEmail, overrides)
	path := filepath.Join(homeDir, ".gitconfig")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write .gitconfig: %w", err)
	}
	return nil
}

// gitconfigPath returns the path for an identity override config file.
// e.g., "~/work/" → ".gitconfig-work"
func gitconfigPath(dir string) string {
	// Strip ~/ prefix and trailing /
	name := strings.TrimPrefix(dir, "~/")
	name = strings.TrimSuffix(name, "/")
	name = strings.ReplaceAll(name, "/", "-")
	return fmt.Sprintf(".gitconfig-%s", name)
}
